version: "3.7"
services:
    www:
        build: .
        container_name: 'loups_garous_webserver'
        restart: 'always'
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        container_name: 'loups_garous_db'
        restart: 'always'
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: loups_garous
            MYSQL_USER: user
            MYSQL_PASSWORD: Licorne2020
            MYSQL_ROOT_PASSWORD: Licorne2020 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'loups_garous_phpmyadmin'
        links: 
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: Licorne2020
            MYSQL_ROOT_PASSWORD: Licorne2020 
        networks:
            - default
volumes:
    persistent: